%% Skew Density/CDF Contaminated Normal %%
function dens = dSNC(y, mu, sigma2, shape, nu)
    
    dens = 2 .* (nu(1) .* normpdf(y, mu, sqrt(sigma2./nu(2))) ...
                       .* normcdf(sqrt(nu(2)) .* shape .* sigma2.^(-1/2) .* (y - mu)) ...
         + (1 - nu(1)) .* normpdf(y, mu, sqrt(sigma2)) ...
                       .* normcdf(shape .* sigma2.^(-1/2) .* (y - mu)));
end